### ISSUE TITLE
"TypeError: undefined is not a function" on client connection

### ISSUE THREAD

**Issue by xavicampa** [schmic/ac-monitor#14]
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: undefined is not a function
    at module.exports (C:\Users\javi\Desktop\ac-monitor\node_modules\ac-server-c
trl\libs\parsers\drivers.js:66:28)
    at wrappedMapper (C:\Users\javi\Desktop\ac-monitor\node_modules\ac-server-ct
rl\node_modules\event-stream\node_modules\map-stream\index.js:84:19)
    at Stream.stream.write (C:\Users\javi\Desktop\ac-monitor\node_modules\ac-ser
ver-ctrl\node_modules\event-stream\node_modules\map-stream\index.js:96:21)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:129:20)
    at Stream.stream.write (C:\Users\javi\Desktop\ac-monitor\node_modules\ac-ser
ver-ctrl\node_modules\event-stream\index.js:54:10)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

**Comment by schmic** [comment]
Please install the latest version of the ac-server-ctrl packe.

Either by "npm remove/install" or by "npm update".

**Comment by xavicampa** [comment]
Yes, npm install fixed it.
