### ISSUE TITLE
Error: Cannot find module 'config' (Debian)

### ISSUE THREAD

**Issue by Ar3xX** [schmic/ac-monitor#3]
Hi Schmic,

somthing goes wrong on my debian server. I got this message if i want to start your tool.

root@h2070992:/usr/local/steam/acMonitor-0.0.1# node acMonitor.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/steam/acMonitor-0.0.1/acMonitor.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Can you give me some instructions please.

**Comment by schmic** [comment]
seems to be working ...
