### ISSUE TITLE
Preset upload broken on validatePreset()

### ISSUE THREAD

**Issue by crashmax** [schmic/ac-monitor#6]
Hi,

First let me thank you for this great work.

I have one issue as I'm not able to set the preset folder. Or I doing something wrong.

This is on Linux (Ubuntu 14.04) with the latest version of  ac-monitor. Stable version is running fine.

This error is thrown as soon as you put in the preset folder name on the webgui.

TypeError: Object #<Object> has no method 'hasPreset'
    at Socket.validatePreset (/home/acserver/acmon/libs/socket-handler-admin.js:14:33)
    at Socket.emit (events.js:98:17)
    at Socket.onevent (/home/acserver/acmon/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/acserver/acmon/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/acserver/acmon/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/acserver/acmon/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/acserver/acmon/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/acserver/acmon/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket (/home/acserver/acmon/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
client disconnected: ye6XtYV0TdkvgupaAAAF

Any help? Thank you very much!

Patrick

**Comment by schmic** [comment]
Need to investigate that a bit further, seems I have refactored a bit too much ...
