### ISSUE TITLE
Error: Configuration property "vr.racedb.url" is not defined

### ISSUE THREAD

**Issue by xavicampa** [schmic/ac-monitor#7]
Hi!

This happens when trying to autostart a preset:

ac-monitor-master\node_modules\config\lib\config.js:177
    throw new Error('Configuration property "' + property + '" is not defined'
          ^
Error: Configuration property "vr.racedb.url" is not defined
    at Config.get (C:\Users\javi\Desktop\ac-monitor-master\node_modules\config\l
ib\config.js:177:11)
    at Object.<anonymous> (C:\Users\javi\Desktop\ac-monitor-master\node_modules\
ac-server-ctrl\libs\plugins\vr-racedb-laptimes.js:2:30)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\javi\Desktop\ac-monitor-master\node_modules\ac-server-ctrl\libs\
server-plugins.js:6:9
    at Array.forEach (native)

Do you need any other extra information? Cheers.

**Comment by schmic** [comment]
That's a plugin/extension to be used within our community I'm developing that app for.

There's a check missing for the property, it should not be "blindly" used. Will fix that ASAP.

**Comment by schmic** [comment]
@xavicampa the timing overview is currently static, only session and remaining time get updated. That's a know "issue" and the next thing I'll work on.
